/*!
 * \file   MFrontBehaviourWizard.hxx
 * \brief
 * \author Thomas Helfer
 * \date   26/02/2018
 */

#ifndef LIB_TFEL_GUI_MFRONTBEHAVIOURWIZARD_HXX
#define LIB_TFEL_GUI_MFRONTBEHAVIOURWIZARD_HXX

#include <memory>
#include <QtWidgets/QWizard>
#include "MFront/BehaviourDSLDescription.hxx"
#include "TFEL/GUI/MFrontBehaviourPage.hxx"

namespace mfront {

  // forward declaration
  struct AbstractBehaviourDSL;

}  // end of namespace mfront

namespace tfel::gui {

  // forward declarations
  struct EditorWidget;
  struct TextEditBase;
  struct MFrontMetaDataPage;
  struct MFrontStandardElastoViscoPlasticityBrickPage;
  struct MFrontAddVariablesPage;
  struct MFrontTemplateGenerationOptionsPage;

  struct MFrontBehaviourWizard : public QWizard {
    //! a simple alias
    using DSLGenerationOptions = MFrontBehaviourPage::DSLGenerationOptions;
    /*!
     * \brief constructor
     * \param[in] w: editor
     * \param[in] cd: current document
     * \param[in] p: parent
     */
    MFrontBehaviourWizard(EditorWidget &,
                          TextEditBase &,
                          QWidget *const p = nullptr);
    //! \brief write the output of the wizard
    virtual void write() const;
    /*!
     * \brief write the options of the brick
     * \param[in] b: brick name
     */
    virtual void writeBehaviourBrickOptions(const QString &) const;
    /*!
     * \return the abstract behaviour dsl generated by the behaviour
     * page.
     */
    virtual std::shared_ptr<mfront::AbstractBehaviourDSL> getBehaviourDSL(
        const DSLGenerationOptions &) const;
    /*!
     * \return the description of abstract behaviour dsl completed by
     * the brick description, if any.
     */
    virtual mfront::BehaviourDSLDescription getBehaviourDSLDescription() const;
    //! \brief destructor
    ~MFrontBehaviourWizard() override;

   protected:
    //! \brief meta data
    MFrontMetaDataPage *md = nullptr;
    //! \brief integration method
    MFrontBehaviourPage *im = nullptr;
    //! \brief add variables page
    MFrontAddVariablesPage *variables = nullptr;
    /*!
     * \brief brick associated to the StandardElastoViscoPlasticity
     * brick
     */
    MFrontStandardElastoViscoPlasticityBrickPage *sevpbp = nullptr;
    /*!
     * \brief page associated with the options used to generate
     * the code template
     */
    MFrontTemplateGenerationOptionsPage *tgop = nullptr;
    //! \brief editor
    EditorWidget &editor;
    //! \brief document
    TextEditBase &d;

   private:
    Q_OBJECT
  };  // end of struct MFrontBehaviourWizard

}  // end of namespace tfel::gui

#endif /* LIB_TFEL_GUI_MFRONTBEHAVIOURWIZARD_HXX */
