/*!
 * \file   MFrontBehaviourWizard.hxx
 * \brief
 * \author Thomas Helfer
 * \date   26/02/2018
 */

#ifndef LIB_TFEL_GUI_MFRONTBEHAVIOURWIZARD_HXX
#define LIB_TFEL_GUI_MFRONTBEHAVIOURWIZARD_HXX

#include <memory>
#include <QtWidgets/QWizard>

namespace mfront {

  // forward declaration
  struct AbstractBehaviourDSL;

}  // end of namespace mfront

namespace tfel {

  namespace gui {

    // forward declarations
    struct EditorWidget;
    struct TextEditBase;
    struct MFrontMetaDataPage;
    struct MFrontBehaviourPage;
    struct MFrontStandardElastoViscoPlasticityBrickPage;
    struct MFrontAddVariablesPage;

    struct MFrontBehaviourWizard : public QWizard {
      /*!
       * \brief constructor
       * \param[in] w: editor
       * \param[in] cd: current document
       * \param[in] p: parent
       */
      MFrontBehaviourWizard(EditorWidget &,
                            TextEditBase &,
                            QWidget *const p = nullptr);
      //! \brief write the output of the wizard
      virtual void write() const;
      /*!
       * \return the abstract behaviour dsl generated by the behaviour
       * page.
       */
      virtual std::shared_ptr<mfront::AbstractBehaviourDSL>
      getBehaviourDSL() const;
      //! destructor
      ~MFrontBehaviourWizard() override;

     protected:
      //! \brief meta data
      MFrontMetaDataPage *md = nullptr;
      //! \brief integration method
      MFrontBehaviourPage *im = nullptr;
      //! \brief add variables page
      MFrontAddVariablesPage *variables = nullptr;
      /*!
       * \brief brick associated to the StandardElastoViscoPlasticity
       * brick
       */
      MFrontStandardElastoViscoPlasticityBrickPage *sevpbp = nullptr;
      //! \brief document
      TextEditBase &d;

     private:
      Q_OBJECT
    };  // end of struct MFrontBehaviourWizard

  }  // end of namespace gui

}  // end of namespace tfel

#endif /* LIB_TFEL_GUI_MFRONTBEHAVIOURWIZARD_HXX */
